### ISSUE TITLE
WIFI connection

### ISSUE THREAD

**Issue by floriank1976** [icalmels/wordclock#1]
Hello, first of all, great Project, thanks a lot for sharing!

I have a problem connecting to my Wifi (WPA2 CCMP).
When i create a Hotpot with my phone, it works, but not with my router.
Have you already heard about this problem?

Thanks in advance
Florian

**Comment by machintrucbidule** [comment]
Hi,

You mean that you're not able to connect on your routeur from the ESP8266, right?

First, you should try closer to your router (ESP8266 aren't powerfull and are quiete impacted by interferences).
Then you should check that your router is having separate 5Ghz and 2.4Ghz wifi networks. Indeed, ESP8266 is only able to connect on 2.4Ghz. On my router ("livebox" from Orange, my ISP), by default 5 and 2.4Ghz network are some kind of "merged" and that's not working with ESP8266. But with both network, and configuring ESP on the 2.4 one that's working fine.

And if still not working, I would advise to ask on a board dedicated to ESP8266 (there 
for instance : https://github.com/esp8266/Arduino)

Regards,
Ivan

**Comment by floriank1976** [comment]
Hi, thanks for your help!
The problem was the force B network. My router was set to only use GN.

BR
Florian
