### ISSUE TITLE
Adding USB-C port

### ISSUE THREAD

**Issue by Almostcompletedprojects** [icalmels/wordclock#3]
Hi! I want to replace the cable by an usb-c port, it should'nt consume more than 3A at 5V so could you upload the original files?
I also want to decrease the overall thickness to consume less filament and change some dimensions to make it fit on a A1mini.

**Comment by machintrucbidule** [comment]
Hi,

I just put the Fusion360's F3D file on printables : https://www.printables.com/model/425721-word-clock-french/files
